### ISSUE TITLE
only saving last row in processChunk

### ISSUE THREAD

**Issue by GodAlmighty990** [beamworks/react-csv-importer#45] opened 2021-08-17 21:05 UTC
Im having an issue where my file is saving only last row ...

```
 processChunk={async (rows, { startIndex }) => {
    // required, receives a list of parsed objects based on defined fields and user column mapping;
    // may be called several times if file is large
    // (if this callback returns a promise, the widget will wait for it before parsing more data)
    console.log(startIndex)
    const array = []
    for (let row of rows) {
      array.push(row)
    //  await myAppMethod(row);
    }
    console.log(array) <--- this array logs full ex. 547, then logs again with 1 object, which is the last row
    await setUpload({...upload, contacts: array}) <--- this array is only showing one object, which is the last row of csv
 console.log('processChunk ran')
 console.log(upload)
  }}
```

**Comment by adenashrudin** [comment] 2021-08-18 04:59
Yess, same with me. For example : I'am have 50 length data, I think to be separated loop with 49 length and 1 in last row.

**Comment by GodAlmighty990** [comment] 2021-08-18 05:01
I think it may have something to do with the delimiters?

**Comment by adenashrudin** [comment] 2021-08-19 03:33
I think have a bugs in last row. I Have tried every possibility and finally I have one solution but is tricky we must add + 1 empty row. If we add 1 empty row at last row everything fine.

**Comment by GodAlmighty990** [comment] 2021-08-19 03:43
Can you show an example of code how your adding an empty row?

**Comment by GodAlmighty990** [comment] 2021-08-19 03:44
It could have something to do with that last pull request. I says that parsing customConfig needs to be passed to the parserPreview to apply custom settings?

**Comment by adenashrudin** [comment] 2021-08-19 03:52
I have no idea about that. I just edited my csv file. 

befere
<img width="715" alt="Screen Shot 2021-08-19 at 10 44 47" src="https://user-images.githubusercontent.com/25833789/130004851-2a115137-5fd8-4cef-a668-abc4e55afc7a.png">

after
<img width="715" alt="Screen Shot 2021-08-19 at 10 44 56" src="https://user-images.githubusercontent.com/25833789/130004869-f8b0e72f-6602-4572-9528-db61e19d0fac.png">

**Comment by unframework** [comment] 2021-08-21 02:07
Hey, thanks for investigating this stuff, sorry for not responding earlier.

Are you expecting `processChunk` to be called only once? It's supposed to be called zero, one or several times - depending on the file size and structure. When receiving the data, you could keep appending it to an array and then use it in the `onComplete` callback.

There are more advanced usage patterns too, but either way I think this is expected behaviour? I can update the docs if that matches up with your situation, or please let me know if I am missing something above?

**Comment by unframework** [comment] 2022-02-10 00:30
I double-checked and it looks like the final import works ok, but the data preview is missing the last line, which needs to be fixed of course. There is an issue #61 that has screenshots/etc demonstrating that, my notes are there. Closing this one, thanks!

**Closed by unframework** 2022-02-10 00:30 UTC
