### ISSUE TITLE
Data handler called twice

### ISSUE THREAD

**Issue by founderblocks-sils** [beamworks/react-csv-importer#103] opened 2023-03-15 12:26 UTC
Hey, I'm using this code to reproduce the issue:

```
<Importer
        dataHandler={async (rows, { startIndex }) => {
          console.log(rows, startIndex);
          return;
        }}
      >
        <ImporterField
          name='test'
          label='test'
        />
      </Importer>
```

When importing a file with 2 lines (a heading line and a value line) I'm getting the callback called TWICE with the same data it seems.

**Comment by unframework** [comment] 2023-03-15 14:32
Interesting, mind sharing the console.log output from this code?

**Comment by MeshanKhosla** [comment] 2023-03-16 19:31
Also having this issue for both `dataHandler` and `processChunk`

**Comment by unframework** [comment] 2023-03-17 03:03
Thanks, that should help me repro! I have a suspicion that this is React 18 related (it has a funny quirk that useEffect runs twice when mounting, by design).

I will try to fix on the weekend, but meanwhile mind checking if this persists when you build the code with NODE_ENV=production?

**Comment by vipersils** [comment] 2023-03-17 07:03
No time to repro right now but in our production deployment it indeed doesnt seem to happen which probably supports your theory

**Comment by sheyDev** [comment] 2023-05-18 06:58
is there a solution for this? Runs twice on every run

**Comment by unframework** [comment] 2023-05-21 13:36
I just pushed version 0.8.1 that should deal with this problem. Please let me know and re-open if the issue still persists, closing meanwhile.

**Closed by unframework** 2023-05-21 13:36 UTC
